// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fybuarobwyysnoxywcos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5YnVhcm9id3l5c25veHl3Y29zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTY5NzEsImV4cCI6MjA2NjMzMjk3MX0.1LERMpHIK-e61uy7_w28h9A-Zlk-qhlsqjQkqZ2RFfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);